name: growing_in_flutter
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  # Hidden Drawer Menu
  hidden_drawer_menu: ^2.0.1
  # Theme Provider | Animate Do | Animated Login UI | The Basics Web
  provider: ^4.3.2+3
  # Curved Navigation Bar
  curved_navigation_bar: ^0.3.7
  # Foldable Navigation Sidebar
  foldable_sidebar: ^1.0.0
  # Foldable Navigation Sidebar
  swipedetector: ^1.2.0
  # Spin Circle Bottom Navigation Bar
  spincircle_bottom_bar: ^1.0.0
  # Plant UI | Meditate UI
  flutter_svg: ^0.19.1
  # Animate Do
  animate_do: ^1.7.5
  # Animate Do | Pet UI
  font_awesome_flutter: ^8.11.0
  # Tic Tac Toe
  google_fonts: ^1.1.1
  # Tic Tac Toe
  avatar_glow: ^1.2.0 
  # Calculator
  math_expressions: ^2.0.2
  # Login Page Bloc Pattern
  rxdart: ^0.25.0 
  # Login Bloc | Weather Bloc
  flutter_bloc: ^6.1.1
  # Login Bloc | Weather Bloc
  equatable: ^1.2.5
  # Weather Bloc | Login Flare 2D UI
  flare_flutter: ^2.0.6
  # Weather Bloc | The Basics Web
  http: ^0.12.2
  # The Basics Web
  responsive_builder: ^0.3.0
  # The Basics Web
  get_it: ^5.0.4
  # The Basics Web
  provider_architecture: ^1.1.1+1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    # Plant UI
    - PlantUI/assets/icons/
    - PlantUI/assets/images/
    # Meditate UI
    - MeditateUI/assets/icons/
    - MeditateUI/assets/images/
    # Tic Tac Tow
    - TicTacToe/assets/images/
    # Weather Bloc
    - WeatherBloc/assets/animations/
    # Login Flare 2D UI
    - LoginFlare2DUI/assets/animations/
    # Pet UI
    - PetUI/assets/images/
    # Flappy Bird
    - FlappyBird/assets/images/
    # The Basics Web 
    - TheBasicsWeb/assets/images/

  fonts:
    # Meditate UI
    - family: Cairo
      fonts:
        - asset: MeditateUI/assets/fonts/Cairo/Cairo-Regular.ttf
        - asset: MeditateUI/assets/fonts/Cairo/Cairo-SemiBold.ttf
          weight: 600
        - asset: MeditateUI/assets/fonts/Cairo/Cairo-Bold.ttf
          weight: 700
        - asset: MeditateUI/assets/fonts/Cairo/Cairo-Black.ttf
          weight: 900
    # Pet UI
    - family: Circular
      fonts:
        - asset: PetUI/assets/fonts/CircularStd-Medium.ttf
        - asset: PetUI/assets/fonts/CircularAir-Light.ttf
          weight: 100
        - asset: PetUI/assets/fonts/CircularStd-Bold.ttf
          weight: 500
    # The Basics Web
    - family: Open Sans
      fonts:
        - asset: TheBasicsWeb/assets/fonts/OpenSans-ExtraBold.ttf
          weight: 800
        - asset: TheBasicsWeb/assets/fonts/OpenSans-Regular.ttf
          weight: 400